language: c

compiler:
  - clang

addons:
  apt:
    packages:
    - libssl-dev
    - libcurl4-gnutls-dev
    - libjson-c-dev
    - liburiparser-dev
    - valgrind
    - check
    - make
    - cmake

script:
  - set -e
  - mkdir debug && cd debug
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make 
  - ctest -T memcheck
  - cd ..
  - mkdir release && cd release
  - cmake ..
  - make
