language: c

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - libssl-dev
    - libcurl3-dev
    - libjson-c-dev
    - liburiparser-dev
    - valgrind
    - check
    - make
    - cmake

script:
  - set -e
  - mkdir debug && cd debug
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make 
  - ./run_tests.sh
  - cd .. && mkdir release && cd release
  - cmake ..
  - make
